---
- name: installing compose extension
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ extensions.compose.version | default ('1.27.4') }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0655'

- name: upload defined compose files
  block:
    - name: create necessary directories for placing docker compose manifests
      file:
        path: "{{ item.destination_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0644'
      with_items: "{{ docker_compose }}"

    - name: transfer defined compose files based on the domain in srv directory
      template:
        src: "{{ item.template_path }}"
        dest: "{{ item.destination_path }}"
        owner: root
        group: root
        mode: '0644'
      with_items: "{{ docker_compose }}"

    - name: bring up the containers based on docker composes
      command: docker-compose up -d
      args:
        chdir: "{{ item.destination_path | dirname }}"
      with_items: "{{ docker_compose }}"
  when:
    - docker_compose | length > 0
