---
- name: configuring iptables
  block:
    - name: creating DOCKER-USER chain
      shell: iptables -n --list DOCKER-USER >/dev/null 2>&1 || iptables -N DOCKER-USER

    - name: creating DOCKER-WHITELIST chain
      shell: iptables -n --list DOCKER-WHITELIST >/dev/null 2>&1 || iptables -N DOCKER-WHITELIST

    - name: flushing existing DOCKER-WHITELIST chain
      iptables:
        chain: DOCKER-WHITELIST
        flush: yes

    - name: dropping all other packets
      iptables:
        chain: DOCKER-WHITELIST
        jump: DROP

    - name: adding DOCKER-WHITELIST into DOCKER-USER
      iptables:
        chain: DOCKER-USER
        jump: DOCKER-WHITELIST
        action: insert
      register: change

    - name: persisting created basic ip4tables rules
      shell: iptables-save > /etc/iptables/rules.v4
      when: change.changed

    - name: persisting created basic ip6tables rules
      shell: ip6tables-save > /etc/iptables/rules.v6
      when: change.changed
  when: configure.iptables
  tags: iptables