---
- include_tasks: 'distributions/{{ ansible_distribution | lower }}.yml'

- name: configure proxy if defined
  include_tasks: proxy.yml
  when:
    - docker_proxy.http is defined
    - docker_proxy.http != ''

- name: login to defined registries
  include_tasks: registries.yml
  when:
    - docker_registries | length > 0

- name: configure a mirror as default registry
  include_tasks: registry.yml
  when:
    - docker_mirror_registry is defined
    - docker_mirror_registry != ""

- name: configure docker networks
  include_tasks: networks.yml
  when:
    - docker_networks is defined

- name: install and configure compose extension
  include_tasks: compose.yml
  when:
    - extensions.compose is defined
