---
- name: create systemd necessary directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: create systemd service config file
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
    owner: root
    group: root
    mode: '0644'

- name: reload systemd daemon
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
