---
- name: adding docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https }}"

- name: adding docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    update_cache: yes
    state: present
    filename: docker
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https }}"

- name: installing main packages
  apt:
    force_apt_get: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https }}"
