---
- name: installing necessary packages
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes
    state: present
    force_apt_get: yes

- name: adding docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https | default(docker_proxy.http) }}"

- name: adding docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    update_cache: yes
    state: present
    filename: docker
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https | default(docker_proxy.http) }}"

- name: installing main packages
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes
    force_apt_get: yes
  environment:
    http_proxy: "{{ docker_proxy.http }}"
    https_proxy: "{{ docker_proxy.https | default(docker_proxy.http) }}"
